myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls'))
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('<slug:slug>', views.post_page, name='single')
]

posts/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("Welcome to the homepage.")
    return render(request, "index.html")

def about(request):
    # return HttpResponse("This is the about page.")
    return render(request, "about.html")

posts/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from .models import Post


# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/list.html', {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/single.html', {'post': post})

posts/templates/posts/list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <h1>Posts</h1>
    <hr>
    <div class="list-group">
        {% for post in posts %}
            <article class="list-item">
                <h3>
                    <a href="{% url 'posts:single' slug=post.slug %}">{{ post.title }}</a>
                </h3>
                <p><small>{{ post.date }}</small></p>
                <p>{{ post.body }}</p>
            </article>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/single.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p><small>{{ post.date }}</small></p>
    <hr>
    <br>
    <p>{{ post.body }}</p>
{% endblock %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About Page</h1>
    <p>Back to <a href="/">Home</a> page.</p>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Welcome to the Homepage</h1>
    <p>Also checkout my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <nav>
        <div class="container">
            <a href="/" class="nav-item">🏠 Home</a>
            <a href="/about" class="nav-item">😎 About</a>
            <a href="{% url 'posts:list' %}" class="nav-item">📰 Posts</a>
        </div>
    </nav>
    <main>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    
</body>
</html>